
version: 2

models:
    - name: ecommerce_orders
      description: "Silver Ecommerce orders table"

    - name: customers
      description: "Extracting Unique customers from Bronze layer "
      

    